[profile.default]
optimizer = true
optimizer_runs = 1000000
evm_version = 'london'
dynamic_test_linking = true
via_ir = true
fs_permissions = [
    { access = 'read', path = './'},
    { access = 'read-write', path = './deployments' }
]
